// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"
	user "go-backend-template/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, _a1
func (_m *UserRepository) Add(ctx context.Context, _a1 user.UserModel) (int64, error) {
	ret := _m.Called(ctx, _a1)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, user.UserModel) int64); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, user.UserModel) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type UserRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//  - ctx context.Context
//  - _a1 user.UserModel
func (_e *UserRepository_Expecter) Add(ctx interface{}, _a1 interface{}) *UserRepository_Add_Call {
	return &UserRepository_Add_Call{Call: _e.mock.On("Add", ctx, _a1)}
}

func (_c *UserRepository_Add_Call) Run(run func(ctx context.Context, _a1 user.UserModel)) *UserRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.UserModel))
	})
	return _c
}

func (_c *UserRepository_Add_Call) Return(_a0 int64, _a1 error) *UserRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetByEmail(ctx context.Context, email string) (user.UserModel, error) {
	ret := _m.Called(ctx, email)

	var r0 user.UserModel
	if rf, ok := ret.Get(0).(func(context.Context, string) user.UserModel); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(user.UserModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//  - ctx context.Context
//  - email string
func (_e *UserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepository_GetByEmail_Call {
	return &UserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetByEmail_Call) Return(_a0 user.UserModel, _a1 error) *UserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetById provides a mock function with given fields: ctx, userId
func (_m *UserRepository) GetById(ctx context.Context, userId int64) (user.UserModel, error) {
	ret := _m.Called(ctx, userId)

	var r0 user.UserModel
	if rf, ok := ret.Get(0).(func(context.Context, int64) user.UserModel); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Get(0).(user.UserModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type UserRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//  - ctx context.Context
//  - userId int64
func (_e *UserRepository_Expecter) GetById(ctx interface{}, userId interface{}) *UserRepository_GetById_Call {
	return &UserRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, userId)}
}

func (_c *UserRepository_GetById_Call) Run(run func(ctx context.Context, userId int64)) *UserRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserRepository_GetById_Call) Return(_a0 user.UserModel, _a1 error) *UserRepository_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *UserRepository) Update(ctx context.Context, _a1 user.UserModel) (int64, error) {
	ret := _m.Called(ctx, _a1)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, user.UserModel) int64); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, user.UserModel) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//  - ctx context.Context
//  - _a1 user.UserModel
func (_e *UserRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *UserRepository_Update_Call {
	return &UserRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *UserRepository_Update_Call) Run(run func(ctx context.Context, _a1 user.UserModel)) *UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.UserModel))
	})
	return _c
}

func (_c *UserRepository_Update_Call) Return(_a0 int64, _a1 error) *UserRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
